[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]
aptPkgs = ["libgl1-mesa-dri", "libglib2.0-0", "libsm6", "libxext6", "libxrender-dev", "libgomp1", "libgthread-2.0-0"]

[phases.install]
cmd = "pip install -r requirements.txt"

[start]
cmd = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"