[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.9.13"

[deploy]
startCommand = "cd api && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"  # optional
restartPolicyType = "on_failure"